name: Node.js CI

on:
  push:
    branches: [ "master", "canvas" ]
  pull_request:
    branches: [ "master", "canvas" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: install python dependecies
      run: pip install flask
    - name: install js dependecies
      run: npm ci
    - name: bundle js code
      run: npx webpack --mode=production
    - name: run test
      run: npm run ssat
